//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISCO.Presentation.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SISCO.Presentation.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silakan pilih agen.
        /// </summary>
        public static string agent_empty {
            get {
                return ResourceManager.GetString("agent_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save changes before create new?.
        /// </summary>
        public static string alert_before_create {
            get {
                return ResourceManager.GetString("alert_before_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silakan pilih data.
        /// </summary>
        public static string alert_choose_data {
            get {
                return ResourceManager.GetString("alert_choose_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohon diisi field yang kosong.
        /// </summary>
        public static string alert_empty_field {
            get {
                return ResourceManager.GetString("alert_empty_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tujuan {0} bukan untuk cabang ini.
        /// </summary>
        public static string check_destination {
            get {
                return ResourceManager.GetString("check_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN sudah terdaftar.
        /// </summary>
        public static string cn_exists {
            get {
                return ResourceManager.GetString("cn_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN harus 12 karakter.
        /// </summary>
        public static string cn_less_12 {
            get {
                return ResourceManager.GetString("cn_less_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact IT Department for further information.
        /// </summary>
        public static string contact_it_dep {
            get {
                return ResourceManager.GetString("contact_it_dep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save with data empty.
        /// </summary>
        public static string data_empty {
            get {
                return ResourceManager.GetString("data_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string default_number {
            get {
                return ResourceManager.GetString("default_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string delete_confirm {
            get {
                return ResourceManager.GetString("delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda yakin akan menghapus data ini?.
        /// </summary>
        public static string delete_confirm_msg {
            get {
                return ResourceManager.GetString("delete_confirm_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert changes and continues with operation?.
        /// </summary>
        public static string dirty_form {
            get {
                return ResourceManager.GetString("dirty_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN tidak diketahui.
        /// </summary>
        public static string empty_cn {
            get {
                return ResourceManager.GetString("empty_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct Username and Password.
        /// </summary>
        public static string enter_correct_login {
            get {
                return ResourceManager.GetString("enter_correct_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to close this application?.
        /// </summary>
        public static string exit_application {
            get {
                return ResourceManager.GetString("exit_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Validation.
        /// </summary>
        public static string form_validation {
            get {
                return ResourceManager.GetString("form_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap go_first {
            get {
                object obj = ResourceManager.GetObject("go_first", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap go_last {
            get {
                object obj = ResourceManager.GetObject("go_last", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap go_next {
            get {
                object obj = ResourceManager.GetObject("go_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap go_previous {
            get {
                object obj = ResourceManager.GetObject("go_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_add_small {
            get {
                object obj = ResourceManager.GetObject("icon_add_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_cancel_small {
            get {
                object obj = ResourceManager.GetObject("icon_cancel_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_delete {
            get {
                object obj = ResourceManager.GetObject("icon_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_delete_small {
            get {
                object obj = ResourceManager.GetObject("icon_delete_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_excel_small {
            get {
                object obj = ResourceManager.GetObject("icon_excel_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_new {
            get {
                object obj = ResourceManager.GetObject("icon_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_print {
            get {
                object obj = ResourceManager.GetObject("icon_print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_print_preview {
            get {
                object obj = ResourceManager.GetObject("icon_print_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_print_small {
            get {
                object obj = ResourceManager.GetObject("icon_print_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_save {
            get {
                object obj = ResourceManager.GetObject("icon_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_save_small {
            get {
                object obj = ResourceManager.GetObject("icon_save_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Username or Password.
        /// </summary>
        public static string incorrect_login {
            get {
                return ResourceManager.GetString("incorrect_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. CN bukan untuk cabang ini.
        /// </summary>
        public static string invalid_stt {
            get {
                return ResourceManager.GetString("invalid_stt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid STT.
        /// </summary>
        public static string invalid_stt_title {
            get {
                return ResourceManager.GetString("invalid_stt_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Account.
        /// </summary>
        public static string invalid_user_account {
            get {
                return ResourceManager.GetString("invalid_user_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sudah dibuatkan invoice.
        /// </summary>
        public static string invoiced {
            get {
                return ResourceManager.GetString("invoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save changes before closing?.
        /// </summary>
        public static string message_save_changes {
            get {
                return ResourceManager.GetString("message_save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap no {
            get {
                object obj = ResourceManager.GetObject("no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has no shipper or consignee name.
        /// </summary>
        public static string no_customer_shipper_consignee {
            get {
                return ResourceManager.GetString("no_customer_shipper_consignee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        public static string no_found_data {
            get {
                return ResourceManager.GetString("no_found_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bukan Transaksi Collect.
        /// </summary>
        public static string not_collect {
            get {
                return ResourceManager.GetString("not_collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;Choose...&gt;&gt;.
        /// </summary>
        public static string null_text {
            get {
                return ResourceManager.GetString("null_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Office_Excel_icon {
            get {
                object obj = ResourceManager.GetObject("Office_Excel_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sudah terdaftar konsolidasi.
        /// </summary>
        public static string registered_consolidation {
            get {
                return ResourceManager.GetString("registered_consolidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sudah terdaftar di inbound.
        /// </summary>
        public static string registered_inbound {
            get {
                return ResourceManager.GetString("registered_inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sudah terdaftar manifest.
        /// </summary>
        public static string registered_manifest {
            get {
                return ResourceManager.GetString("registered_manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rep_Cal_Icon {
            get {
                object obj = ResourceManager.GetObject("Rep_Cal_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Confirmation.
        /// </summary>
        public static string save_confirmation {
            get {
                return ResourceManager.GetString("save_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes has been successfully saved.
        /// </summary>
        public static string save_success {
            get {
                return ResourceManager.GetString("save_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cannot be changed, please check tracking status.
        /// </summary>
        public static string status_invalid {
            get {
                return ResourceManager.GetString("status_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add STT/Consol No..
        /// </summary>
        public static string stt_detail_empty {
            get {
                return ResourceManager.GetString("stt_detail_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. CN sudah masuk outbound.
        /// </summary>
        public static string stt_waybilled {
            get {
                return ResourceManager.GetString("stt_waybilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap system_search {
            get {
                object obj = ResourceManager.GetObject("system_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap system_search_small {
            get {
                object obj = ResourceManager.GetObject("system_search_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string title_save_changes {
            get {
                return ResourceManager.GetString("title_save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total transaksi harus sama dengan jumlah yang dibayarkan.
        /// </summary>
        public static string total_invoice {
            get {
                return ResourceManager.GetString("total_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty..
        /// </summary>
        public static string username_cannot_be_empty {
            get {
                return ResourceManager.GetString("username_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap view_refresh {
            get {
                object obj = ResourceManager.GetObject("view_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap view_refresh_small {
            get {
                object obj = ResourceManager.GetObject("view_refresh_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap yes {
            get {
                object obj = ResourceManager.GetObject("yes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
