//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corporate.Presentation.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Corporate.Presentation.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silakan pilih data.
        /// </summary>
        public static string alert_choose_data {
            get {
                return ResourceManager.GetString("alert_choose_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill required field.
        /// </summary>
        public static string alert_empty_field {
            get {
                return ResourceManager.GetString("alert_empty_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter product key..
        /// </summary>
        public static string alert_empty_product_key {
            get {
                return ResourceManager.GetString("alert_empty_product_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application has been corrupted..
        /// </summary>
        public static string application_corrupted {
            get {
                return ResourceManager.GetString("application_corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN sudah terdaftar.
        /// </summary>
        public static string cn_exists {
            get {
                return ResourceManager.GetString("cn_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN harus 12 karakter.
        /// </summary>
        public static string cn_less_12 {
            get {
                return ResourceManager.GetString("cn_less_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact PT. Globalindo Dua Satu Ekspres IT Support.
        /// </summary>
        public static string contact_it_support {
            get {
                return ResourceManager.GetString("contact_it_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        public static string delete_confirm {
            get {
                return ResourceManager.GetString("delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda yakin akan menghapus data ini?.
        /// </summary>
        public static string delete_confirm_msg {
            get {
                return ResourceManager.GetString("delete_confirm_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert changes and continues with operation?.
        /// </summary>
        public static string dirty_form {
            get {
                return ResourceManager.GetString("dirty_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty.
        /// </summary>
        public static string empty_username {
            get {
                return ResourceManager.GetString("empty_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this application?.
        /// </summary>
        public static string exit_question {
            get {
                return ResourceManager.GetString("exit_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your franchise account was not found..
        /// </summary>
        public static string franchise_account_not_found {
            get {
                return ResourceManager.GetString("franchise_account_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been disabled..
        /// </summary>
        public static string inactive_product_key {
            get {
                return ResourceManager.GetString("inactive_product_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username and password.
        /// </summary>
        public static string invalid_login {
            get {
                return ResourceManager.GetString("invalid_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid product key..
        /// </summary>
        public static string invalid_product_key {
            get {
                return ResourceManager.GetString("invalid_product_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. CN bukan untuk cabang ini.
        /// </summary>
        public static string invalid_stt {
            get {
                return ResourceManager.GetString("invalid_stt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid STT.
        /// </summary>
        public static string invalid_stt_title {
            get {
                return ResourceManager.GetString("invalid_stt_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save changes before closing?.
        /// </summary>
        public static string message_save_changes {
            get {
                return ResourceManager.GetString("message_save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found.
        /// </summary>
        public static string no_found_data {
            get {
                return ResourceManager.GetString("no_found_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Office_Excel_icon {
            get {
                object obj = ResourceManager.GetObject("Office_Excel_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add POD.
        /// </summary>
        public static string pod_data_empty {
            get {
                return ResourceManager.GetString("pod_data_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap print_preview {
            get {
                object obj = ResourceManager.GetObject("print_preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rep_Cal_Icon {
            get {
                object obj = ResourceManager.GetObject("Rep_Cal_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Confirmation.
        /// </summary>
        public static string save_confirmation {
            get {
                return ResourceManager.GetString("save_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes has been successfully saved.
        /// </summary>
        public static string save_success {
            get {
                return ResourceManager.GetString("save_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap system_search_small {
            get {
                object obj = ResourceManager.GetObject("system_search_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string title_confirmation {
            get {
                return ResourceManager.GetString("title_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Product Key.
        /// </summary>
        public static string title_inactive_product_key {
            get {
                return ResourceManager.GetString("title_inactive_product_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string title_information {
            get {
                return ResourceManager.GetString("title_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Product Key.
        /// </summary>
        public static string title_invalid_product_key {
            get {
                return ResourceManager.GetString("title_invalid_product_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string title_login_failed {
            get {
                return ResourceManager.GetString("title_login_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Confirmation.
        /// </summary>
        public static string void_confirm {
            get {
                return ResourceManager.GetString("void_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda yakin ingin membatalkan POD ini?.
        /// </summary>
        public static string void_confirm_msg {
            get {
                return ResourceManager.GetString("void_confirm_msg", resourceCulture);
            }
        }
    }
}
